### ISSUE TITLE
MD WIDGETS: Extract the code from Riopod and place it into the markdown_widgets package

### ISSUE THREAD

**Issue by tonypioneer** [anusii/markdown_widget_builder#1]
## Description

In [Riopod](https://github.com/anusii/riopod/issues/19), we defined and implemented a series of markdown-like syntax to generate widgets on the survey page. Now, we plan to extract this part of the code into a standalone package named *markdown_widgets*, making it easier to maintain and accessible for use in other code.

This issue requires migrating the code from Riopod into this repository and creating it as a standalone package.

**Comment by gjwgit** [comment]
Need to review and structure the code.

For discussion

- [ ] `lib/markdown-widgets.dart` will list just the exports.
- [ ] Every functionality split from the single large file
- [ ] Folders for features, widgets, utils, etc.

**Comment by gjwgit** [comment]
This can represent the first version. Other issues can be created to work on from here.

Can be closed once PR merged.
