### ISSUE TITLE
MD WIDGETS: Save user input data to a local JSON file

### ISSUE THREAD

**Issue by tonypioneer** [anusii/markdown_widget_builder#17]
## Description

Add an additional parameter to the Submit button and let users save the user input data as a local JSON file. Make this submission method the default, while also providing options for users to submit via POST to a URL or POD.

**Comment by gjwgit** [comment]
For the example app perhaps simply pass a function that always saves the survey in a fixed file.

Or even a function that simply displays a popup containing the JSON from the survey.

The aim of the example is to be very simple, and not fancy.
