### ISSUE TITLE
MD-WIDGETS: Support CHROME target

### ISSUE THREAD

**Issue by gjwgit** [anusii/markdown_widget_builder#21]
## Description

Currently seeing a few issues with `flutter run -d chrome`. Otherwise it is working great. Thanks.

## Why

So that a web-based app functions fully with the package.

### VIDEO DOES NOT LOAD

![Image](https://github.com/user-attachments/assets/0ca0e461-d359-47b1-9b0b-efb8af5cf04a)

![Image](https://github.com/user-attachments/assets/587f4cef-b1ed-4537-bf61-796f9df93c29)

### SUBMIT FAILS

Survey 3, tap on SUBMIT results in

![Image](https://github.com/user-attachments/assets/d10c991d-a596-4b20-bac3-5d64506e65ac)

**Comment by tonypioneer** [comment]
This issue has been fixed.
<img width="1366" alt="image" src="https://github.com/user-attachments/assets/17d0c507-ac35-4edf-ab05-e1ecd766cbe9">
