### ISSUE TITLE
MD WIDGETS: Add a file name confirmation dialogue before saving data to a local file when using the Chrome browser

### ISSUE THREAD

**Issue by tonypioneer** [anusii/markdown_widget_builder#33]
## Description

Currently when the users clicks the save button, the JSON file will be automatically downloaded to the Downloads folders with the default file name. Add a file name confirmation dialogue before the file is downloaded.

**Comment by tonypioneer** [comment]
![image](https://github.com/user-attachments/assets/778fa889-c2cd-46b7-bb33-485a0d588828)

**Comment by gjwgit** [comment]
Works well. Thanks Tony.
